#subscription_id      = "your-subscription-id"
resource_group_name  = "rg-fw-demo"
location             = "East US"
firewall_name        = "demo-fw"
vnet_name            = "demo-fw-vnet"
vnet_address_space   = "10.10.0.0/16"
subnet_cidr          = "10.10.1.0/24"
